<?php
  $lang['number']		= 'RÉfÉrence';
  $lang['date']			= 'Date de facturation';
  $lang['due']			= 'Date d\'ÉchÉance';
  $lang['to']			= 'FacturÉ À';
  $lang['from']			= '';
  $lang['product']		= 'Produit';
  $lang['qty']			= '';
  $lang['price']		= 'Prix';
  $lang['discount']		= 'Réduction';
  $lang['vat']			= 'Cuve';
  $lang['total']		= 'Total';
  $lang['page']			= 'Page';
  $lang['page_of']		= 'de';
?>